apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      restartPolicy: Always
      initContainers:
        - name: git-cloner
          image: alpine/git
          command:
            - /bin/sh
            - -c
          #args:
          #  - git clone https://github.com/amrbaraka/priv.git /test
          args:
           - |
             git config --global credential.helper store && \
             echo "https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com" > ~/.git-credentials && \
             git clone ${GIT_URL} /test
          env:
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-repo-secret
                  key: username
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-creds-secret
                  key: password
            - name: GIT_URL
              valueFrom:
                secretKeyRef:
                  name: git-creds-secret
                  key: url
          volumeMounts:
            - name: git-repo
              mountPath: /test
      containers:
        - name: deployer
          image: bitnami/kubectl:latest
          command: ["/bin/sh", "-c", "sleep infinity"]
          volumeMounts:
            - name: git-repo
              mountPath: /test
            - name: config-volume
              mountPath: /configs
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: config-volume
          configMap:
            name: app-variables-cm
