apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: console-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: console-sa
    namespace: default
roleRef:
  kind: Role
  name: console-role
  apiGroup: rbac.authorization.k8s.io
