apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: executor-rolebinding
subjects:
  - kind: ServiceAccount
    name: executor-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: executor-role
  apiGroup: rbac.authorization.k8s.io
