apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-rolebinding-global
subjects:
  - kind: ServiceAccount
    name: console-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: console-role
  apiGroup: rbac.authorization.k8s.io
