apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: console-sa
      containers:
        - name: frontend
          image: public.ecr.aws/g8c8r6q0/frontend:0.59
          ports:
            - containerPort: 8080
          env:
          - name: DOMAIN_NAME
            valueFrom:
              configMapKeyRef:
                name: domain-name-cm
                key: DOMAIN_NAME
